language: node_js
node_js:
  - "node"
  - "4.2"
  - "0.12"
after_script: '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && npm run test-browser-sauce || true'
deploy:
  provider: npm
  email: ivan.goncharov.ua@gmail.com
  api_key:
    secure: tmsTIdZiH1A5NI0Qeyq/QeqM+al9EsrXWLyZKLZQvyb60+yqFx1SuILszYGjbEMRq30cJs1MJz0BENad1XuOZGqgcvHjPDIjs/JBh9odxhfM7L8a1/G54aDzRTz+qac1m3E1qoT4Gg/8bVoskQdwZIVodV/za27nL3Rg+8zdc2H0WOqO1VI7/F1GIN+tdOb5VREcgYE1lXIPEpmMdjppqAWl6dzUFgLkpivqfUDB6Go9iFzwy1xwKeKgN8/SNCioNMMFkiLDMdscxvxKLb+tsZc+IYMXSarUuBCxrzoq/SMC1kJZL7v/72TExLv9YTmf8igpEjCbxsRxUx7sTEi76mv2rHRI5pb/tu7pin09KDl0pk/hlqUx/ySMPsFRBAgizf9SlREsHQxqVFkWdPXgu6o/T06ZmVJHpIJCrBYyUbgHGWO7QPONUGvZIhKcbG03v+f+pJUYuk7QY1gnqdQhwNij/NUsx+TaEY0Pkq6ZvQRowJZep/HgKWKhA5MobeaBHdTupqUiUMwQkKEOP4/kWGSv4Esh6Ojh7bprPv+PemPbar0WDFF8e02ZN3tUEJ0YmpqN5N58tmIhd/IZQD5m8oY3ArxiB2oV/aRI2hZhtHhiGLjOg7vbm1TbBqULipK3kJvrt89j9gZ4er7Rq8uPRjLDe1G7J0eMuh8TJGe/Zio=
  on:
    tags: true
    repo: lucybot/api-spec-converter
