language: node_js
node_js:
  - "node"
  - "4.2"
  - "0.12"
after_script: '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && npm run test-browser-sauce || true'
deploy:
  provider: npm
  email: ivan.goncharov.ua@gmail.com
  api_key:
    secure: gY6qtfQo3hEyEmJ3f3QhzciHo5r8HHW2peYBFzkyXHpW2LBU5P0FPJVYZqTHFKvQn6pyucp1E7YI/kiE/uAFFhBM4lYtH3OXuRMj4GKqOQ+rYiMDM7w3aeGVELA7BWva/c58Yhd3kXYtW4E/eOiDmlshS8abbTK4mSe7SKWL41n9WpKuMlpD9rcn1LWGPwnS3lQ0eVMwraoN5SYnHDzMDuWwYOiOgQ8/7eRI0kGUfvAZMrDpq/0fJEoIQOVey8Rp+52S4fzB8xLVPY/0T9ahflkPL/jWlPu/afm1Ew+DijeqOIn//CixNjLjFlTGN1Ijhqytr6Hf9rNdCE+kNVH7YHAnkHfZYJ+N5i75EpLnS2XZqldBnrNR3FtRw+gmXaKw8Qtv/mCIIlVehb4NHrNky2s7dcyrzSEi+wnoNWzIUkvt7s/9CIqCYOlnzN1vf2r4QGIQyzjRybJv6G5adk1iqwAiIC4QFYKfeKfrKlw4UdBlNlJYZlkjHLj8KhVc7Ph+9PAXIKd92ne/ZkchqZfvXdEDV/s6J/4HAgjQ9RON77IaJHBHNqI1EvyMmtEvzMvdn4mmSuoy73WieHYaGWphw+v/ZQgC31oVO4CGxaPcY0A3bIWAt0iZozvrPh4MX7F1ZNuo2WJwTM6DDDAznj+0TyV9etznyEd1WaRInmRTfH8=
  on:
    tags: true
    repo: lucybot/api-spec-converter
